{% set data = load_setup_py_data() %}

package:
  name: automated-metadata-generation
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/USGS-Astrogeology/automated-metadata-generation.git

build:
  string: "{{ GIT_DESCRIBE_NUMBER }}_dev"
  noarch: python
  
extra:
  channels:
    - conda-forge

requirements:
  build:
    - python
    - gdal
  run:
    - python
    - gdal
    - geojson
    - gis-metadata-parser>=2.0
    - jsonschema
    - pvl>=1.3.0
    - psycopg2
    - pyproj
    - pystac>=1.1.0,<1.2
    - pyyaml
    - shapely
    - sqlalchemy>=1.4,<1.5
    - yaml

test:
  imports:
    - amg

about:
  home: http://github.com/USGS-Astrogeology/automated-metadata-generation
  license: CC0
  license_file: LICENSE.md
  sumamry: generation FGDC and STAC metadata from hetereogeneous sources