name: amg
channels:
  - conda-forge
dependencies:
  - python
  - gdal
  - geojson
  - jsonschema
  - pvl >= 1.3.0
  - psycopg2
  - pyproj
  - pystac >= 1.0.0, <1.2
  - pyyaml
  - shapely
  - sqlalchemy >= 1.4, < 1.5
  - pip
  - yaml
  - pip:
      - gis-metadata-parser >= 1.2.6
