name: amg

dependencies:
  - python
  - gdal
  - geojson
  - jsonschema
  - pvl
  - psycopg2
  - pyfakefs
  - pyproj
  - pystac
  - pytest
  - pytest-cov
  - pyyaml
  - shapely
  - sphinx
  - sqlalchemy >= 1.4, < 1.5
  - pip
  - pyaml
  - pip:
      - gis-metadata-parser
