name: amg

dependencies:
  - python
  - gdal
  - jsonschema
  - pvl
  - psycopg2
  - pyproj
  - pystac
  - pyyaml
  - shapely
  - sqlalchemy >= 1.4, < 1.5
  - pip
  - yaml
  - pip:
      - gis-metadata-parser
